# Generated by Django 4.0.3 on 2022-04-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0003_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='average',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
        ),
    ]
