# Generated by Django 4.0.3 on 2022-04-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0005_ratings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='project_image',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
