# Generated by Django 4.0.3 on 2022-04-10 04:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0009_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='Design',
            new_name='design',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='Usability',
            new_name='userbility',
        ),
        migrations.AlterField(
            model_name='post',
            name='project_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePhoto',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
