# Generated by Django 4.0.3 on 2022-04-10 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awardsapp', '0010_rename_content_ratings_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awardsapp.profile'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awardsapp.post'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='average',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20, verbose_name='average'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='content',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='design',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='design'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='userbility',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='userbility'),
        ),
    ]
